name: Deploy static website to S3
on:
  push:
    branches:
      - master
jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy code to S3
        uses: reggionick/s3-deploy@v4
        with:
          folder: src
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.AWS_REGION }}
          files-to-include: '.*/*,*/*,**'
